//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosClients.CosmosReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Starship", Namespace="http://schemas.datacontract.org/2004/07/CosmicAdventureDTO.DataTransferObjects")]
    [System.SerializableAttribute()]
    public partial class Starship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CosmosClients.CosmosReference.Person[] CrewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int GoldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShipPowerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CosmosClients.CosmosReference.Person[] Crew {
            get {
                return this.CrewField;
            }
            set {
                if ((object.ReferenceEquals(this.CrewField, value) != true)) {
                    this.CrewField = value;
                    this.RaisePropertyChanged("Crew");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Gold {
            get {
                return this.GoldField;
            }
            set {
                if ((this.GoldField.Equals(value) != true)) {
                    this.GoldField = value;
                    this.RaisePropertyChanged("Gold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShipPower {
            get {
                return this.ShipPowerField;
            }
            set {
                if ((this.ShipPowerField.Equals(value) != true)) {
                    this.ShipPowerField = value;
                    this.RaisePropertyChanged("ShipPower");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/CosmicAdventureDTO.DataTransferObjects")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NickField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nick {
            get {
                return this.NickField;
            }
            set {
                if ((object.ReferenceEquals(this.NickField, value) != true)) {
                    this.NickField = value;
                    this.RaisePropertyChanged("Nick");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StarSystem", Namespace="http://schemas.datacontract.org/2004/07/CosmicAdventureDTO.DataTransferObjects")]
    [System.SerializableAttribute()]
    public partial class StarSystem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BaseDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BaseDistance {
            get {
                return this.BaseDistanceField;
            }
            set {
                if ((this.BaseDistanceField.Equals(value) != true)) {
                    this.BaseDistanceField = value;
                    this.RaisePropertyChanged("BaseDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CosmosReference.ICosmos")]
    public interface ICosmos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmos/InitializeGame", ReplyAction="http://tempuri.org/ICosmos/InitializeGameResponse")]
        void InitializeGame();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmos/SendStarship", ReplyAction="http://tempuri.org/ICosmos/SendStarshipResponse")]
        CosmosClients.CosmosReference.Starship SendStarship(CosmosClients.CosmosReference.Starship starship, string systemName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmos/GetSystem", ReplyAction="http://tempuri.org/ICosmos/GetSystemResponse")]
        CosmosClients.CosmosReference.StarSystem GetSystem();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICosmos/GetStarship", ReplyAction="http://tempuri.org/ICosmos/GetStarshipResponse")]
        CosmosClients.CosmosReference.Starship GetStarship(int money);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICosmosChannel : CosmosClients.CosmosReference.ICosmos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CosmosClient : System.ServiceModel.ClientBase<CosmosClients.CosmosReference.ICosmos>, CosmosClients.CosmosReference.ICosmos {
        
        public CosmosClient() {
        }
        
        public CosmosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CosmosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CosmosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CosmosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InitializeGame() {
            base.Channel.InitializeGame();
        }
        
        public CosmosClients.CosmosReference.Starship SendStarship(CosmosClients.CosmosReference.Starship starship, string systemName) {
            return base.Channel.SendStarship(starship, systemName);
        }
        
        public CosmosClients.CosmosReference.StarSystem GetSystem() {
            return base.Channel.GetSystem();
        }
        
        public CosmosClients.CosmosReference.Starship GetStarship(int money) {
            return base.Channel.GetStarship(money);
        }
    }
}
